"""add follow_up_note

Revision ID: c75a6102ef74
Revises: f7e44a8d1c41
Create Date: 2026-09-29 14:35:13.846762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c75a6102ef74'
down_revision: Union[str, Sequence[str], None] = 'f7e44a8d1c41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_up_note',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('action_date', sa.Date(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follow_up_note')
    # ### end Alembic commands ###
